@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package es.degrassi.mmreborn.common.integration.ingredient;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;