// Visit the wiki for more info - https://kubejs.com/

ServerEvents.recipes(event => {
     event.recipes.modular_machinery_reborn.machine_recipe("mmr:testing", 5)
         .height(100)
         .requireEnergy(20, 8, 8)
         .produceItem('4x modular_machinery_reborn:modularium', 8 + 18 + 18 + 18 + 10 + 22 + 8, 8)
         .requireItem('minecraft:iron_ingot', 8 + 18, 8)
         .requireItem('minecraft:gold_ingot', 8 + 18 + 18, 8)
         .requireItem('minecraft:redstone', 8 + 18, 8 + 18)
         .requireItem('minecraft:glowstone_dust', 8 + 18 + 18, 8 + 18)
     event.recipes.modular_machinery_reborn.machine_recipe("modular_machinery_reborn:alloy_smelter", 120)
         .requireEnergy(100)
         .produceItem('1x minecraft:diamond')
         .requireItem('32x minecraft:coal')
         .requireItem('8x minecraft:tnt')
     event.recipes.modular_machinery_reborn.machine_recipe("modular_machinery_reborn:power_transformer", 1)
         .produceEnergy(1000)
     event.recipes.modular_machinery_reborn.machine_recipe("mmr:testing", 20)
         .requireEnergy(100000, 8, 8)
         .requireItem("2x modular_machinery_reborn:casing_plain", 8 + 18, 8)
         .lootTable('modular_machinery_reborn:machines_loot', 8 + 18 + 18 + 18 + 10 + 22 + 8, 8)
         .produceFluid('1x minecraft:lava', 0.5, 8 + 18 + 18 + 18 + 10 + 22 + 8 + 18, 8)
         .requireHeight('[-60, 100]', 8 + 18, 8 + 18)

    event.recipes.modular_machinery_reborn.machine_recipe("mmr:test3", 20)
        .produceExperience(100)
        .renderProgress(false)
        .height(8 + 8 + 3 + 9 + 3 + 9 + 3)
    event.recipes.modular_machinery_reborn.machine_recipe("mmr:test4", 15)
        .height(8 + 18 + 8 + 3 + 9 + 3 + 9 + 3)
        .requireExperience(100)
        .produceItem("1x minecraft:diamond", 0.35, 8, 8)
    event.recipes.modular_machinery_reborn.machine_recipe("mmr:test5", 20)
        .height(8 + 18 + 8 + 3 + 9 + 3 + 9 + 3)
        .produceItem("1x minecraft:diamond", 8, 8)
    event.recipes.modular_machinery_reborn.machine_recipe("mmr:testing89", 20)
        .progressX(55)
        .progressY(25)
        .width(200)
        .height(75)
        .produceItem('2x minecraft:diamond', 102, 8)
        .requireEnergy(100000, 8, 8)
        .requireFluid('1x mekanism:sulfuric_acid', 28, 8)
        .requireFluid('1x mekanism:hydrofluoric_acid', 28, 8+18)
        .priority(100)
    event.recipes.modular_machinery_reborn.machine_recipe("mmr:testing89", 20)
        .progressX(55)
        .progressY(25)
        .width(200)
        .height(75)
        .produceItem('2x minecraft:diamond', 102, 8)
        .requireEnergy(100000, 8, 8)
        .requireChemical('1x mekanism:sulfuric_acid', 28, 8)
        .requireChemical('1x mekanism:hydrofluoric_acid', 28, 8+18)
        .priority(100)
    event.recipes.modular_machinery_reborn.machine_recipe("mmr:testing89", 20)
        .progressX(55)
        .progressY(25)
        .width(200)
        .height(75)
        .requireItem('2x #c:ingots/steel', 8 + 20, 8)
        .requireEnergy(100000, 8, 8)
        .produceChemical('1x mekanism:sulfuric_acid', 102, 8)
        .produceChemical('1x mekanism:hydrofluoric_acid', 102, 8+18)
        .priority(100)
    event.recipes.modular_machinery_reborn.machine_recipe("mmr:testing89", 20)
        .progressX(55)
        .progressY(25)
        .width(200)
        .height(75)
        .requireItem('2x #minecraft:planks', 8 + 20, 8)
        .requireEnergy(100000, 8, 8)
        .produceFluid('1x mekanism:sulfuric_acid', 102, 8)
        .produceFluid('1x mekanism:hydrofluoric_acid', 102, 8+18)
        .produceSource(1000, 102 +18, 8+18)
        .priority(100)
});

