@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package es.degrassi.mmreborn.common.registration;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;